.TH ankee 1 ankee
.SH NAME
Ankee \- quick japanese subtitle -> anki flashcard converter
.SH SYNOPSIS
.B ankee
.IR text
.RB [path/to/audio]
.SH DESCRIPTION
.B Ankee
is a simple to use tool to search definitions in the JMDict and push them into an anki card
.SH SHORTCUTS
.SS Movement
.INDENT 0.0
.TP
.B hjkl
Let you move inside squares
.TP
.B HJKL
Let you move between squares
.SP
.SS Interacting with text
.INDENT 0.0
.TP
.B <space>
Selects currently hovered item
.TP
.B <enter>
Pushes a Word+Reading+Meaning pair to the final output
.TP
.B v
Enters visual mode to select words
.TP
.B 0
Goes to the start of the string
.TP
.SS Exit
.INDENT 0.0
.TP
.B q
Exits without doing anything
.TP
.B O
Pushes entire string, no prompt
.TP
.B I
Pushes entire string, gui prompt
.TP

